kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "helm-chart.fullname" . }}-reader
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
rules:
  - apiGroups: ["", "extensions", "apps"]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
  {{- include "helm-chart.labels" . | nindent 4 }}
roleRef:
  kind: Role
  name: {{ include "helm-chart.fullname" . }}-reader
  apiGroup: ""
subjects:
  - kind: ServiceAccount
    name: {{ include "helm-chart.fullname" . }}
    apiGroup: ""
