apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm-chart.fullname" . }}-config
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
data:
  application.yaml: |-
    spring:
      application:
        name: order-service
    ---
    spring:
      profiles: dev
      datasource:
        driver-class-name: org.h2.Driver
    ---
    spring:
      profiles: prod
      datasource:
        url: jdbc:postgresql://{{ .Release.Name }}-spring-boot-db:5432/{{.Values.spring-boot-db.postgresqlDatabase}}
        username: {{.Values.spring-boot-db.postgresqlUsername}}
        password: {{.Values.spring-boot-db.postgresqlPassword}}
        driver-class-name: org.postgresql.Driver
